---
# Default variables
workspace: "/opt/app"
docker_registry: "harbor.registry.local"
project_namespace: "jenkins"
image_name: "mylocalimage"


# Computing Image tags
frontend_image: "{{ docker_registry }}/{{ project_namespace }}/{{ image_name }}:frontend_{{ build_number }}"
backend_image: "{{ docker_registry }}/{{ project_namespace }}/{{ image_name }}:backend_{{ build_number }}"
