- name: Login to Docker registry
  community.docker.docker_login:
    username: "admin"
    password: "Harbor12345"
    registry: "your-registry-url"  # Add your registry URL if not Docker Hub

- name: Pull latest images
  command: "docker compose --env-file {{ env_file }} pull"
  args:
    chdir: "{{ workspace }}"

- name: Deploy application
  command: "docker compose --env-file {{ env_file }} up -d"
  args:
    chdir: "{{ workspace }}"