---
- name: Pull and deploy Docker images
  community.docker.docker_compose_v2:
    project_src: "{{ workspace }}"       # directory with docker-compose.yml
    pull: yes
    up: yes
    detached: yes
    login:
      username: "admin"
      password: "Harbor12345"


- name: Pull latest images
  command: "docker compose --env-file {{ env_file }} pull"
  args:
    chdir: "{{ workspace }}"

- name: Deploy application
  command: "docker compose --env-file {{ env_file }} up -d"
  args:
    chdir: "{{ workspace }}"