# roles/app_deployer/tasks/04_cleanup.yml
---

- name: Prune only dangling Docker images
  become: yes
  community.docker.docker_prune:
    images:    yes    # remove dangling/untagged images
    containers: no    # leave containers alone
    networks:   no
    volumes:    no
