# roles/app_deployer/tasks/04_cleanup.yml
---

- name: Prune only dangling Docker images
  become: yes                     # ensure docker permissions
  shell: docker image prune -f
  args:
    warn: false                   # suppress deprecation warnings
