- name: Debug build number
  debug:
    msg: "Build number is {{ build_number }}"

- name: Nuclear cleanup + pull fresh images
  shell: |

    docker images prune -a -f
    

    docker pull {{ docker_registry }}/{{ project_namespace }}/{{ image_name }}:frontend_{{ build_number }}
    docker pull {{ docker_registry }}/{{ project_namespace }}/{{ image_name }}:backend_{{ build_number }}
    

    docker pull {{ docker_registry }}/{{ project_namespace }}/{{ image_name }}:frontend_{{ build_number|int - 1 }} || true
    docker pull {{ docker_registry }}/{{ project_namespace }}/{{ image_name }}:backend_{{ build_number|int - 1 }} || true
  args:
    executable: /bin/bash