# roles/app_deployer/tasks/04_cleanup.yml
---

- name: Prune only dangling Docker images
  community.docker.docker_prune:
    images:   yes      # remove dangling (untagged) images
    containers: no
    networks:   no
    volumes:    no
  become: yes         # or remove if your ansible user is in the docker group
