# SPDX-License-Identifier: MIT-0
---
- name: Prepare deployment workspace
  import_tasks: 01_setup.yml
  tags: setup

- name: Handle configuration files
  import_tasks: 02_configs.yml
  tags: configs

- name: Deploy containers
  import_tasks: 03_deploy.yml
  tags: deploy

- name: Clean up old images
  import_tasks: 04_cleanup.yml
  tags: cleanup

- name: Verify deployment
  import_tasks: 05_verify.yml
  tags: verify